job('First-Maven-Project-Via-DSL') {
    description("Greeteng job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/mladen92/Jenkins_Course.git", master)
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'greetings/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
 // link for documentation http://jenkinsci.github.io/job-dsl-plugin/#