pipeline {
      agent any
      stages {
            stage('Build Application Stage') {
                  steps {
                        echo 'Tomcat sample first stage'
                        sh 'mvn -f java-tomcat-sample/pom.xml clean package'
                  }
                  post{
                        success{
                        echo "Now Archiving the Artifacts..."
                        archiveArtifacts artifacts: '**/*.war'
                        }
                  }
                }
                  stage('Deploy In Staging Env'){
                  steps{
                     build job: 'Deploy_Aplication_Staging_Env'
                     }
                 }
                    stage('Deploy to Production'){
                             steps{
                                 timeout(time:5, unit:'DAYS'){
                                     input message:'Approve PRODUCTION Deployment?'
                                 }
                                 build job: 'Deploy_Application_Prod_Env'
                             }
                         }
             }
          }
